#### Path ####
BASE_PATH: "/nas/RAW/BCI/Datasets/BCI_Competition_IV_2b"
LOG_PATH: "./logs/BCICompet2b"
CKPT_PATH: "./checkpoints"

#### Setting step ####
SEED: 42
GPU_NUM: "1"
num_workers: 0

#### Training step ####
EPOCHS: 500
batch_size: 512
lr: 2.0e-3

weight_decay: 0.075


#### Experiment variable ####
task: "BCICompet2b"
num_classes: 2
num_channels: 3
downsampling: 0

num_subjects: 9
sampling_rate: 250
target_subject: 0
is_test: False

#### Etc ###
log_etc: "Baseline"
momentum: 0.9
